/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthVerifyRouteImport } from './routes/auth/verify'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as LearnerLayoutRouteRouteImport } from './routes/learner/_layout/route'
import { Route as InstructorLayoutRouteRouteImport } from './routes/instructor/_layout/route'
import { Route as LearnerLayoutIndexRouteImport } from './routes/learner/_layout/index'
import { Route as InstructorLayoutIndexRouteImport } from './routes/instructor/_layout/index'
import { Route as InstructorLayoutCoursesIndexRouteImport } from './routes/instructor/_layout/courses/index'
import { Route as InstructorLayoutCoursesCourseIdManageRouteImport } from './routes/instructor/_layout/courses/$courseId/manage'

const LearnerRouteImport = createFileRoute('/learner')()
const InstructorRouteImport = createFileRoute('/instructor')()

const LearnerRoute = LearnerRouteImport.update({
  id: '/learner',
  path: '/learner',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorRoute = InstructorRouteImport.update({
  id: '/instructor',
  path: '/instructor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const LearnerLayoutRouteRoute = LearnerLayoutRouteRouteImport.update({
  id: '/_layout',
  getParentRoute: () => LearnerRoute,
} as any)
const InstructorLayoutRouteRoute = InstructorLayoutRouteRouteImport.update({
  id: '/_layout',
  getParentRoute: () => InstructorRoute,
} as any)
const LearnerLayoutIndexRoute = LearnerLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LearnerLayoutRouteRoute,
} as any)
const InstructorLayoutIndexRoute = InstructorLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InstructorLayoutRouteRoute,
} as any)
const InstructorLayoutCoursesIndexRoute =
  InstructorLayoutCoursesIndexRouteImport.update({
    id: '/courses/',
    path: '/courses/',
    getParentRoute: () => InstructorLayoutRouteRoute,
  } as any)
const InstructorLayoutCoursesCourseIdManageRoute =
  InstructorLayoutCoursesCourseIdManageRouteImport.update({
    id: '/courses/$courseId/manage',
    path: '/courses/$courseId/manage',
    getParentRoute: () => InstructorLayoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/instructor': typeof InstructorLayoutRouteRouteWithChildren
  '/learner': typeof LearnerLayoutRouteRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/auth/': typeof AuthIndexRoute
  '/instructor/': typeof InstructorLayoutIndexRoute
  '/learner/': typeof LearnerLayoutIndexRoute
  '/instructor/courses': typeof InstructorLayoutCoursesIndexRoute
  '/instructor/courses/$courseId/manage': typeof InstructorLayoutCoursesCourseIdManageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/instructor': typeof InstructorLayoutIndexRoute
  '/learner': typeof LearnerLayoutIndexRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/auth': typeof AuthIndexRoute
  '/instructor/courses': typeof InstructorLayoutCoursesIndexRoute
  '/instructor/courses/$courseId/manage': typeof InstructorLayoutCoursesCourseIdManageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/instructor': typeof InstructorRouteWithChildren
  '/instructor/_layout': typeof InstructorLayoutRouteRouteWithChildren
  '/learner': typeof LearnerRouteWithChildren
  '/learner/_layout': typeof LearnerLayoutRouteRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/auth/': typeof AuthIndexRoute
  '/instructor/_layout/': typeof InstructorLayoutIndexRoute
  '/learner/_layout/': typeof LearnerLayoutIndexRoute
  '/instructor/_layout/courses/': typeof InstructorLayoutCoursesIndexRoute
  '/instructor/_layout/courses/$courseId/manage': typeof InstructorLayoutCoursesCourseIdManageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/instructor'
    | '/learner'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify'
    | '/auth/'
    | '/instructor/'
    | '/learner/'
    | '/instructor/courses'
    | '/instructor/courses/$courseId/manage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/instructor'
    | '/learner'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify'
    | '/auth'
    | '/instructor/courses'
    | '/instructor/courses/$courseId/manage'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/instructor'
    | '/instructor/_layout'
    | '/learner'
    | '/learner/_layout'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify'
    | '/auth/'
    | '/instructor/_layout/'
    | '/learner/_layout/'
    | '/instructor/_layout/courses/'
    | '/instructor/_layout/courses/$courseId/manage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  InstructorRoute: typeof InstructorRouteWithChildren
  LearnerRoute: typeof LearnerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/learner': {
      id: '/learner'
      path: '/learner'
      fullPath: '/learner'
      preLoaderRoute: typeof LearnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor': {
      id: '/instructor'
      path: '/instructor'
      fullPath: '/instructor'
      preLoaderRoute: typeof InstructorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/learner/_layout': {
      id: '/learner/_layout'
      path: '/learner'
      fullPath: '/learner'
      preLoaderRoute: typeof LearnerLayoutRouteRouteImport
      parentRoute: typeof LearnerRoute
    }
    '/instructor/_layout': {
      id: '/instructor/_layout'
      path: '/instructor'
      fullPath: '/instructor'
      preLoaderRoute: typeof InstructorLayoutRouteRouteImport
      parentRoute: typeof InstructorRoute
    }
    '/learner/_layout/': {
      id: '/learner/_layout/'
      path: '/'
      fullPath: '/learner/'
      preLoaderRoute: typeof LearnerLayoutIndexRouteImport
      parentRoute: typeof LearnerLayoutRouteRoute
    }
    '/instructor/_layout/': {
      id: '/instructor/_layout/'
      path: '/'
      fullPath: '/instructor/'
      preLoaderRoute: typeof InstructorLayoutIndexRouteImport
      parentRoute: typeof InstructorLayoutRouteRoute
    }
    '/instructor/_layout/courses/': {
      id: '/instructor/_layout/courses/'
      path: '/courses'
      fullPath: '/instructor/courses'
      preLoaderRoute: typeof InstructorLayoutCoursesIndexRouteImport
      parentRoute: typeof InstructorLayoutRouteRoute
    }
    '/instructor/_layout/courses/$courseId/manage': {
      id: '/instructor/_layout/courses/$courseId/manage'
      path: '/courses/$courseId/manage'
      fullPath: '/instructor/courses/$courseId/manage'
      preLoaderRoute: typeof InstructorLayoutCoursesCourseIdManageRouteImport
      parentRoute: typeof InstructorLayoutRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface InstructorLayoutRouteRouteChildren {
  InstructorLayoutIndexRoute: typeof InstructorLayoutIndexRoute
  InstructorLayoutCoursesIndexRoute: typeof InstructorLayoutCoursesIndexRoute
  InstructorLayoutCoursesCourseIdManageRoute: typeof InstructorLayoutCoursesCourseIdManageRoute
}

const InstructorLayoutRouteRouteChildren: InstructorLayoutRouteRouteChildren = {
  InstructorLayoutIndexRoute: InstructorLayoutIndexRoute,
  InstructorLayoutCoursesIndexRoute: InstructorLayoutCoursesIndexRoute,
  InstructorLayoutCoursesCourseIdManageRoute:
    InstructorLayoutCoursesCourseIdManageRoute,
}

const InstructorLayoutRouteRouteWithChildren =
  InstructorLayoutRouteRoute._addFileChildren(
    InstructorLayoutRouteRouteChildren,
  )

interface InstructorRouteChildren {
  InstructorLayoutRouteRoute: typeof InstructorLayoutRouteRouteWithChildren
}

const InstructorRouteChildren: InstructorRouteChildren = {
  InstructorLayoutRouteRoute: InstructorLayoutRouteRouteWithChildren,
}

const InstructorRouteWithChildren = InstructorRoute._addFileChildren(
  InstructorRouteChildren,
)

interface LearnerLayoutRouteRouteChildren {
  LearnerLayoutIndexRoute: typeof LearnerLayoutIndexRoute
}

const LearnerLayoutRouteRouteChildren: LearnerLayoutRouteRouteChildren = {
  LearnerLayoutIndexRoute: LearnerLayoutIndexRoute,
}

const LearnerLayoutRouteRouteWithChildren =
  LearnerLayoutRouteRoute._addFileChildren(LearnerLayoutRouteRouteChildren)

interface LearnerRouteChildren {
  LearnerLayoutRouteRoute: typeof LearnerLayoutRouteRouteWithChildren
}

const LearnerRouteChildren: LearnerRouteChildren = {
  LearnerLayoutRouteRoute: LearnerLayoutRouteRouteWithChildren,
}

const LearnerRouteWithChildren =
  LearnerRoute._addFileChildren(LearnerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  InstructorRoute: InstructorRouteWithChildren,
  LearnerRoute: LearnerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
