/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as LayoutRouteRouteImport } from './routes/_layout/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthVerifyRouteImport } from './routes/auth/verify'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as InstructorLayoutRouteRouteImport } from './routes/instructor/_layout/route'
import { Route as MeetingsMeetingsIdIndexRouteImport } from './routes/meetings/$meetingsId/index'
import { Route as InstructorLayoutIndexRouteImport } from './routes/instructor/_layout/index'
import { Route as LayoutSettingsIndexRouteImport } from './routes/_layout/settings/index'
import { Route as LayoutSessionsIndexRouteImport } from './routes/_layout/sessions/index'
import { Route as LayoutInstructorsIndexRouteImport } from './routes/_layout/instructors/index'
import { Route as LayoutHomeIndexRouteImport } from './routes/_layout/home/index'
import { Route as LayoutCoursesIndexRouteImport } from './routes/_layout/courses/index'
import { Route as LayoutChatsIndexRouteImport } from './routes/_layout/chats/index'
import { Route as InstructorLayoutSessionsIndexRouteImport } from './routes/instructor/_layout/sessions/index'
import { Route as InstructorLayoutPaymentsIndexRouteImport } from './routes/instructor/_layout/payments/index'
import { Route as InstructorLayoutCoursesIndexRouteImport } from './routes/instructor/_layout/courses/index'
import { Route as InstructorLayoutChatsIndexRouteImport } from './routes/instructor/_layout/chats/index'
import { Route as LayoutInstructorsInstructorIdIndexRouteImport } from './routes/_layout/instructors/$instructorId/index'
import { Route as LayoutCoursesCourseIdIndexRouteImport } from './routes/_layout/courses/$courseId/index'
import { Route as LayoutCoursesCourseIdLearnIndexRouteImport } from './routes/_layout/courses/$courseId/learn/index'
import { Route as InstructorLayoutCoursesCourseIdManageRouteImport } from './routes/instructor/_layout/courses/$courseId/manage'

const InstructorRouteImport = createFileRoute('/instructor')()

const InstructorRoute = InstructorRouteImport.update({
  id: '/instructor',
  path: '/instructor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRouteRoute = LayoutRouteRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const InstructorLayoutRouteRoute = InstructorLayoutRouteRouteImport.update({
  id: '/_layout',
  getParentRoute: () => InstructorRoute,
} as any)
const MeetingsMeetingsIdIndexRoute = MeetingsMeetingsIdIndexRouteImport.update({
  id: '/meetings/$meetingsId/',
  path: '/meetings/$meetingsId/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorLayoutIndexRoute = InstructorLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InstructorLayoutRouteRoute,
} as any)
const LayoutSettingsIndexRoute = LayoutSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutSessionsIndexRoute = LayoutSessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutInstructorsIndexRoute = LayoutInstructorsIndexRouteImport.update({
  id: '/instructors/',
  path: '/instructors/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutHomeIndexRoute = LayoutHomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutCoursesIndexRoute = LayoutCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutChatsIndexRoute = LayoutChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const InstructorLayoutSessionsIndexRoute =
  InstructorLayoutSessionsIndexRouteImport.update({
    id: '/sessions/',
    path: '/sessions/',
    getParentRoute: () => InstructorLayoutRouteRoute,
  } as any)
const InstructorLayoutPaymentsIndexRoute =
  InstructorLayoutPaymentsIndexRouteImport.update({
    id: '/payments/',
    path: '/payments/',
    getParentRoute: () => InstructorLayoutRouteRoute,
  } as any)
const InstructorLayoutCoursesIndexRoute =
  InstructorLayoutCoursesIndexRouteImport.update({
    id: '/courses/',
    path: '/courses/',
    getParentRoute: () => InstructorLayoutRouteRoute,
  } as any)
const InstructorLayoutChatsIndexRoute =
  InstructorLayoutChatsIndexRouteImport.update({
    id: '/chats/',
    path: '/chats/',
    getParentRoute: () => InstructorLayoutRouteRoute,
  } as any)
const LayoutInstructorsInstructorIdIndexRoute =
  LayoutInstructorsInstructorIdIndexRouteImport.update({
    id: '/instructors/$instructorId/',
    path: '/instructors/$instructorId/',
    getParentRoute: () => LayoutRouteRoute,
  } as any)
const LayoutCoursesCourseIdIndexRoute =
  LayoutCoursesCourseIdIndexRouteImport.update({
    id: '/courses/$courseId/',
    path: '/courses/$courseId/',
    getParentRoute: () => LayoutRouteRoute,
  } as any)
const LayoutCoursesCourseIdLearnIndexRoute =
  LayoutCoursesCourseIdLearnIndexRouteImport.update({
    id: '/courses/$courseId/learn/',
    path: '/courses/$courseId/learn/',
    getParentRoute: () => LayoutRouteRoute,
  } as any)
const InstructorLayoutCoursesCourseIdManageRoute =
  InstructorLayoutCoursesCourseIdManageRouteImport.update({
    id: '/courses/$courseId/manage',
    path: '/courses/$courseId/manage',
    getParentRoute: () => InstructorLayoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/instructor': typeof InstructorLayoutRouteRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/auth/': typeof AuthIndexRoute
  '/chats': typeof LayoutChatsIndexRoute
  '/courses': typeof LayoutCoursesIndexRoute
  '/home': typeof LayoutHomeIndexRoute
  '/instructors': typeof LayoutInstructorsIndexRoute
  '/sessions': typeof LayoutSessionsIndexRoute
  '/settings': typeof LayoutSettingsIndexRoute
  '/instructor/': typeof InstructorLayoutIndexRoute
  '/meetings/$meetingsId': typeof MeetingsMeetingsIdIndexRoute
  '/courses/$courseId': typeof LayoutCoursesCourseIdIndexRoute
  '/instructors/$instructorId': typeof LayoutInstructorsInstructorIdIndexRoute
  '/instructor/chats': typeof InstructorLayoutChatsIndexRoute
  '/instructor/courses': typeof InstructorLayoutCoursesIndexRoute
  '/instructor/payments': typeof InstructorLayoutPaymentsIndexRoute
  '/instructor/sessions': typeof InstructorLayoutSessionsIndexRoute
  '/instructor/courses/$courseId/manage': typeof InstructorLayoutCoursesCourseIdManageRoute
  '/courses/$courseId/learn': typeof LayoutCoursesCourseIdLearnIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/instructor': typeof InstructorLayoutIndexRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/auth': typeof AuthIndexRoute
  '/chats': typeof LayoutChatsIndexRoute
  '/courses': typeof LayoutCoursesIndexRoute
  '/home': typeof LayoutHomeIndexRoute
  '/instructors': typeof LayoutInstructorsIndexRoute
  '/sessions': typeof LayoutSessionsIndexRoute
  '/settings': typeof LayoutSettingsIndexRoute
  '/meetings/$meetingsId': typeof MeetingsMeetingsIdIndexRoute
  '/courses/$courseId': typeof LayoutCoursesCourseIdIndexRoute
  '/instructors/$instructorId': typeof LayoutInstructorsInstructorIdIndexRoute
  '/instructor/chats': typeof InstructorLayoutChatsIndexRoute
  '/instructor/courses': typeof InstructorLayoutCoursesIndexRoute
  '/instructor/payments': typeof InstructorLayoutPaymentsIndexRoute
  '/instructor/sessions': typeof InstructorLayoutSessionsIndexRoute
  '/instructor/courses/$courseId/manage': typeof InstructorLayoutCoursesCourseIdManageRoute
  '/courses/$courseId/learn': typeof LayoutCoursesCourseIdLearnIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/instructor': typeof InstructorRouteWithChildren
  '/instructor/_layout': typeof InstructorLayoutRouteRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/auth/': typeof AuthIndexRoute
  '/_layout/chats/': typeof LayoutChatsIndexRoute
  '/_layout/courses/': typeof LayoutCoursesIndexRoute
  '/_layout/home/': typeof LayoutHomeIndexRoute
  '/_layout/instructors/': typeof LayoutInstructorsIndexRoute
  '/_layout/sessions/': typeof LayoutSessionsIndexRoute
  '/_layout/settings/': typeof LayoutSettingsIndexRoute
  '/instructor/_layout/': typeof InstructorLayoutIndexRoute
  '/meetings/$meetingsId/': typeof MeetingsMeetingsIdIndexRoute
  '/_layout/courses/$courseId/': typeof LayoutCoursesCourseIdIndexRoute
  '/_layout/instructors/$instructorId/': typeof LayoutInstructorsInstructorIdIndexRoute
  '/instructor/_layout/chats/': typeof InstructorLayoutChatsIndexRoute
  '/instructor/_layout/courses/': typeof InstructorLayoutCoursesIndexRoute
  '/instructor/_layout/payments/': typeof InstructorLayoutPaymentsIndexRoute
  '/instructor/_layout/sessions/': typeof InstructorLayoutSessionsIndexRoute
  '/instructor/_layout/courses/$courseId/manage': typeof InstructorLayoutCoursesCourseIdManageRoute
  '/_layout/courses/$courseId/learn/': typeof LayoutCoursesCourseIdLearnIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/instructor'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify'
    | '/auth/'
    | '/chats'
    | '/courses'
    | '/home'
    | '/instructors'
    | '/sessions'
    | '/settings'
    | '/instructor/'
    | '/meetings/$meetingsId'
    | '/courses/$courseId'
    | '/instructors/$instructorId'
    | '/instructor/chats'
    | '/instructor/courses'
    | '/instructor/payments'
    | '/instructor/sessions'
    | '/instructor/courses/$courseId/manage'
    | '/courses/$courseId/learn'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/instructor'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify'
    | '/auth'
    | '/chats'
    | '/courses'
    | '/home'
    | '/instructors'
    | '/sessions'
    | '/settings'
    | '/meetings/$meetingsId'
    | '/courses/$courseId'
    | '/instructors/$instructorId'
    | '/instructor/chats'
    | '/instructor/courses'
    | '/instructor/payments'
    | '/instructor/sessions'
    | '/instructor/courses/$courseId/manage'
    | '/courses/$courseId/learn'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/auth'
    | '/instructor'
    | '/instructor/_layout'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify'
    | '/auth/'
    | '/_layout/chats/'
    | '/_layout/courses/'
    | '/_layout/home/'
    | '/_layout/instructors/'
    | '/_layout/sessions/'
    | '/_layout/settings/'
    | '/instructor/_layout/'
    | '/meetings/$meetingsId/'
    | '/_layout/courses/$courseId/'
    | '/_layout/instructors/$instructorId/'
    | '/instructor/_layout/chats/'
    | '/instructor/_layout/courses/'
    | '/instructor/_layout/payments/'
    | '/instructor/_layout/sessions/'
    | '/instructor/_layout/courses/$courseId/manage'
    | '/_layout/courses/$courseId/learn/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRouteRoute: typeof LayoutRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  InstructorRoute: typeof InstructorRouteWithChildren
  MeetingsMeetingsIdIndexRoute: typeof MeetingsMeetingsIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/instructor': {
      id: '/instructor'
      path: '/instructor'
      fullPath: '/instructor'
      preLoaderRoute: typeof InstructorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/instructor/_layout': {
      id: '/instructor/_layout'
      path: '/instructor'
      fullPath: '/instructor'
      preLoaderRoute: typeof InstructorLayoutRouteRouteImport
      parentRoute: typeof InstructorRoute
    }
    '/meetings/$meetingsId/': {
      id: '/meetings/$meetingsId/'
      path: '/meetings/$meetingsId'
      fullPath: '/meetings/$meetingsId'
      preLoaderRoute: typeof MeetingsMeetingsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/_layout/': {
      id: '/instructor/_layout/'
      path: '/'
      fullPath: '/instructor/'
      preLoaderRoute: typeof InstructorLayoutIndexRouteImport
      parentRoute: typeof InstructorLayoutRouteRoute
    }
    '/_layout/settings/': {
      id: '/_layout/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/sessions/': {
      id: '/_layout/sessions/'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof LayoutSessionsIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/instructors/': {
      id: '/_layout/instructors/'
      path: '/instructors'
      fullPath: '/instructors'
      preLoaderRoute: typeof LayoutInstructorsIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/home/': {
      id: '/_layout/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof LayoutHomeIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/courses/': {
      id: '/_layout/courses/'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof LayoutCoursesIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/chats/': {
      id: '/_layout/chats/'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof LayoutChatsIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/instructor/_layout/sessions/': {
      id: '/instructor/_layout/sessions/'
      path: '/sessions'
      fullPath: '/instructor/sessions'
      preLoaderRoute: typeof InstructorLayoutSessionsIndexRouteImport
      parentRoute: typeof InstructorLayoutRouteRoute
    }
    '/instructor/_layout/payments/': {
      id: '/instructor/_layout/payments/'
      path: '/payments'
      fullPath: '/instructor/payments'
      preLoaderRoute: typeof InstructorLayoutPaymentsIndexRouteImport
      parentRoute: typeof InstructorLayoutRouteRoute
    }
    '/instructor/_layout/courses/': {
      id: '/instructor/_layout/courses/'
      path: '/courses'
      fullPath: '/instructor/courses'
      preLoaderRoute: typeof InstructorLayoutCoursesIndexRouteImport
      parentRoute: typeof InstructorLayoutRouteRoute
    }
    '/instructor/_layout/chats/': {
      id: '/instructor/_layout/chats/'
      path: '/chats'
      fullPath: '/instructor/chats'
      preLoaderRoute: typeof InstructorLayoutChatsIndexRouteImport
      parentRoute: typeof InstructorLayoutRouteRoute
    }
    '/_layout/instructors/$instructorId/': {
      id: '/_layout/instructors/$instructorId/'
      path: '/instructors/$instructorId'
      fullPath: '/instructors/$instructorId'
      preLoaderRoute: typeof LayoutInstructorsInstructorIdIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/courses/$courseId/': {
      id: '/_layout/courses/$courseId/'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof LayoutCoursesCourseIdIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/courses/$courseId/learn/': {
      id: '/_layout/courses/$courseId/learn/'
      path: '/courses/$courseId/learn'
      fullPath: '/courses/$courseId/learn'
      preLoaderRoute: typeof LayoutCoursesCourseIdLearnIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/instructor/_layout/courses/$courseId/manage': {
      id: '/instructor/_layout/courses/$courseId/manage'
      path: '/courses/$courseId/manage'
      fullPath: '/instructor/courses/$courseId/manage'
      preLoaderRoute: typeof InstructorLayoutCoursesCourseIdManageRouteImport
      parentRoute: typeof InstructorLayoutRouteRoute
    }
  }
}

interface LayoutRouteRouteChildren {
  LayoutChatsIndexRoute: typeof LayoutChatsIndexRoute
  LayoutCoursesIndexRoute: typeof LayoutCoursesIndexRoute
  LayoutHomeIndexRoute: typeof LayoutHomeIndexRoute
  LayoutInstructorsIndexRoute: typeof LayoutInstructorsIndexRoute
  LayoutSessionsIndexRoute: typeof LayoutSessionsIndexRoute
  LayoutSettingsIndexRoute: typeof LayoutSettingsIndexRoute
  LayoutCoursesCourseIdIndexRoute: typeof LayoutCoursesCourseIdIndexRoute
  LayoutInstructorsInstructorIdIndexRoute: typeof LayoutInstructorsInstructorIdIndexRoute
  LayoutCoursesCourseIdLearnIndexRoute: typeof LayoutCoursesCourseIdLearnIndexRoute
}

const LayoutRouteRouteChildren: LayoutRouteRouteChildren = {
  LayoutChatsIndexRoute: LayoutChatsIndexRoute,
  LayoutCoursesIndexRoute: LayoutCoursesIndexRoute,
  LayoutHomeIndexRoute: LayoutHomeIndexRoute,
  LayoutInstructorsIndexRoute: LayoutInstructorsIndexRoute,
  LayoutSessionsIndexRoute: LayoutSessionsIndexRoute,
  LayoutSettingsIndexRoute: LayoutSettingsIndexRoute,
  LayoutCoursesCourseIdIndexRoute: LayoutCoursesCourseIdIndexRoute,
  LayoutInstructorsInstructorIdIndexRoute:
    LayoutInstructorsInstructorIdIndexRoute,
  LayoutCoursesCourseIdLearnIndexRoute: LayoutCoursesCourseIdLearnIndexRoute,
}

const LayoutRouteRouteWithChildren = LayoutRouteRoute._addFileChildren(
  LayoutRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface InstructorLayoutRouteRouteChildren {
  InstructorLayoutIndexRoute: typeof InstructorLayoutIndexRoute
  InstructorLayoutChatsIndexRoute: typeof InstructorLayoutChatsIndexRoute
  InstructorLayoutCoursesIndexRoute: typeof InstructorLayoutCoursesIndexRoute
  InstructorLayoutPaymentsIndexRoute: typeof InstructorLayoutPaymentsIndexRoute
  InstructorLayoutSessionsIndexRoute: typeof InstructorLayoutSessionsIndexRoute
  InstructorLayoutCoursesCourseIdManageRoute: typeof InstructorLayoutCoursesCourseIdManageRoute
}

const InstructorLayoutRouteRouteChildren: InstructorLayoutRouteRouteChildren = {
  InstructorLayoutIndexRoute: InstructorLayoutIndexRoute,
  InstructorLayoutChatsIndexRoute: InstructorLayoutChatsIndexRoute,
  InstructorLayoutCoursesIndexRoute: InstructorLayoutCoursesIndexRoute,
  InstructorLayoutPaymentsIndexRoute: InstructorLayoutPaymentsIndexRoute,
  InstructorLayoutSessionsIndexRoute: InstructorLayoutSessionsIndexRoute,
  InstructorLayoutCoursesCourseIdManageRoute:
    InstructorLayoutCoursesCourseIdManageRoute,
}

const InstructorLayoutRouteRouteWithChildren =
  InstructorLayoutRouteRoute._addFileChildren(
    InstructorLayoutRouteRouteChildren,
  )

interface InstructorRouteChildren {
  InstructorLayoutRouteRoute: typeof InstructorLayoutRouteRouteWithChildren
}

const InstructorRouteChildren: InstructorRouteChildren = {
  InstructorLayoutRouteRoute: InstructorLayoutRouteRouteWithChildren,
}

const InstructorRouteWithChildren = InstructorRoute._addFileChildren(
  InstructorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRouteRoute: LayoutRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  InstructorRoute: InstructorRouteWithChildren,
  MeetingsMeetingsIdIndexRoute: MeetingsMeetingsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
