/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as LayoutRouteRouteImport } from './routes/_layout/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthVerifyRouteImport } from './routes/auth/verify'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as InstructorLayoutRouteRouteImport } from './routes/instructor/_layout/route'
import { Route as InstructorLayoutIndexRouteImport } from './routes/instructor/_layout/index'
import { Route as LayoutSessionsIndexRouteImport } from './routes/_layout/sessions/index'
import { Route as LayoutMessagesIndexRouteImport } from './routes/_layout/messages/index'
import { Route as LayoutHomeIndexRouteImport } from './routes/_layout/home/index'
import { Route as LayoutCoursesIndexRouteImport } from './routes/_layout/courses/index'
import { Route as LayoutAccountIndexRouteImport } from './routes/_layout/account/index'
import { Route as InstructorLayoutSessionsIndexRouteImport } from './routes/instructor/_layout/sessions/index'
import { Route as InstructorLayoutMessagesIndexRouteImport } from './routes/instructor/_layout/messages/index'
import { Route as InstructorLayoutCoursesIndexRouteImport } from './routes/instructor/_layout/courses/index'
import { Route as InstructorLayoutAccountIndexRouteImport } from './routes/instructor/_layout/account/index'
import { Route as LayoutCoursesCourseIdIndexRouteImport } from './routes/_layout/courses/$courseId/index'
import { Route as LayoutCoursesCourseIdLearnIndexRouteImport } from './routes/_layout/courses/$courseId/learn/index'
import { Route as InstructorLayoutCoursesCourseIdManageRouteImport } from './routes/instructor/_layout/courses/$courseId/manage'

const InstructorRouteImport = createFileRoute('/instructor')()

const InstructorRoute = InstructorRouteImport.update({
  id: '/instructor',
  path: '/instructor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRouteRoute = LayoutRouteRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const InstructorLayoutRouteRoute = InstructorLayoutRouteRouteImport.update({
  id: '/_layout',
  getParentRoute: () => InstructorRoute,
} as any)
const InstructorLayoutIndexRoute = InstructorLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InstructorLayoutRouteRoute,
} as any)
const LayoutSessionsIndexRoute = LayoutSessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutMessagesIndexRoute = LayoutMessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutHomeIndexRoute = LayoutHomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutCoursesIndexRoute = LayoutCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutAccountIndexRoute = LayoutAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const InstructorLayoutSessionsIndexRoute =
  InstructorLayoutSessionsIndexRouteImport.update({
    id: '/sessions/',
    path: '/sessions/',
    getParentRoute: () => InstructorLayoutRouteRoute,
  } as any)
const InstructorLayoutMessagesIndexRoute =
  InstructorLayoutMessagesIndexRouteImport.update({
    id: '/messages/',
    path: '/messages/',
    getParentRoute: () => InstructorLayoutRouteRoute,
  } as any)
const InstructorLayoutCoursesIndexRoute =
  InstructorLayoutCoursesIndexRouteImport.update({
    id: '/courses/',
    path: '/courses/',
    getParentRoute: () => InstructorLayoutRouteRoute,
  } as any)
const InstructorLayoutAccountIndexRoute =
  InstructorLayoutAccountIndexRouteImport.update({
    id: '/account/',
    path: '/account/',
    getParentRoute: () => InstructorLayoutRouteRoute,
  } as any)
const LayoutCoursesCourseIdIndexRoute =
  LayoutCoursesCourseIdIndexRouteImport.update({
    id: '/courses/$courseId/',
    path: '/courses/$courseId/',
    getParentRoute: () => LayoutRouteRoute,
  } as any)
const LayoutCoursesCourseIdLearnIndexRoute =
  LayoutCoursesCourseIdLearnIndexRouteImport.update({
    id: '/courses/$courseId/learn/',
    path: '/courses/$courseId/learn/',
    getParentRoute: () => LayoutRouteRoute,
  } as any)
const InstructorLayoutCoursesCourseIdManageRoute =
  InstructorLayoutCoursesCourseIdManageRouteImport.update({
    id: '/courses/$courseId/manage',
    path: '/courses/$courseId/manage',
    getParentRoute: () => InstructorLayoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/instructor': typeof InstructorLayoutRouteRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/auth/': typeof AuthIndexRoute
  '/account': typeof LayoutAccountIndexRoute
  '/courses': typeof LayoutCoursesIndexRoute
  '/home': typeof LayoutHomeIndexRoute
  '/messages': typeof LayoutMessagesIndexRoute
  '/sessions': typeof LayoutSessionsIndexRoute
  '/instructor/': typeof InstructorLayoutIndexRoute
  '/courses/$courseId': typeof LayoutCoursesCourseIdIndexRoute
  '/instructor/account': typeof InstructorLayoutAccountIndexRoute
  '/instructor/courses': typeof InstructorLayoutCoursesIndexRoute
  '/instructor/messages': typeof InstructorLayoutMessagesIndexRoute
  '/instructor/sessions': typeof InstructorLayoutSessionsIndexRoute
  '/instructor/courses/$courseId/manage': typeof InstructorLayoutCoursesCourseIdManageRoute
  '/courses/$courseId/learn': typeof LayoutCoursesCourseIdLearnIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/instructor': typeof InstructorLayoutIndexRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/auth': typeof AuthIndexRoute
  '/account': typeof LayoutAccountIndexRoute
  '/courses': typeof LayoutCoursesIndexRoute
  '/home': typeof LayoutHomeIndexRoute
  '/messages': typeof LayoutMessagesIndexRoute
  '/sessions': typeof LayoutSessionsIndexRoute
  '/courses/$courseId': typeof LayoutCoursesCourseIdIndexRoute
  '/instructor/account': typeof InstructorLayoutAccountIndexRoute
  '/instructor/courses': typeof InstructorLayoutCoursesIndexRoute
  '/instructor/messages': typeof InstructorLayoutMessagesIndexRoute
  '/instructor/sessions': typeof InstructorLayoutSessionsIndexRoute
  '/instructor/courses/$courseId/manage': typeof InstructorLayoutCoursesCourseIdManageRoute
  '/courses/$courseId/learn': typeof LayoutCoursesCourseIdLearnIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/instructor': typeof InstructorRouteWithChildren
  '/instructor/_layout': typeof InstructorLayoutRouteRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/auth/': typeof AuthIndexRoute
  '/_layout/account/': typeof LayoutAccountIndexRoute
  '/_layout/courses/': typeof LayoutCoursesIndexRoute
  '/_layout/home/': typeof LayoutHomeIndexRoute
  '/_layout/messages/': typeof LayoutMessagesIndexRoute
  '/_layout/sessions/': typeof LayoutSessionsIndexRoute
  '/instructor/_layout/': typeof InstructorLayoutIndexRoute
  '/_layout/courses/$courseId/': typeof LayoutCoursesCourseIdIndexRoute
  '/instructor/_layout/account/': typeof InstructorLayoutAccountIndexRoute
  '/instructor/_layout/courses/': typeof InstructorLayoutCoursesIndexRoute
  '/instructor/_layout/messages/': typeof InstructorLayoutMessagesIndexRoute
  '/instructor/_layout/sessions/': typeof InstructorLayoutSessionsIndexRoute
  '/instructor/_layout/courses/$courseId/manage': typeof InstructorLayoutCoursesCourseIdManageRoute
  '/_layout/courses/$courseId/learn/': typeof LayoutCoursesCourseIdLearnIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/instructor'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify'
    | '/auth/'
    | '/account'
    | '/courses'
    | '/home'
    | '/messages'
    | '/sessions'
    | '/instructor/'
    | '/courses/$courseId'
    | '/instructor/account'
    | '/instructor/courses'
    | '/instructor/messages'
    | '/instructor/sessions'
    | '/instructor/courses/$courseId/manage'
    | '/courses/$courseId/learn'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/instructor'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify'
    | '/auth'
    | '/account'
    | '/courses'
    | '/home'
    | '/messages'
    | '/sessions'
    | '/courses/$courseId'
    | '/instructor/account'
    | '/instructor/courses'
    | '/instructor/messages'
    | '/instructor/sessions'
    | '/instructor/courses/$courseId/manage'
    | '/courses/$courseId/learn'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/auth'
    | '/instructor'
    | '/instructor/_layout'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify'
    | '/auth/'
    | '/_layout/account/'
    | '/_layout/courses/'
    | '/_layout/home/'
    | '/_layout/messages/'
    | '/_layout/sessions/'
    | '/instructor/_layout/'
    | '/_layout/courses/$courseId/'
    | '/instructor/_layout/account/'
    | '/instructor/_layout/courses/'
    | '/instructor/_layout/messages/'
    | '/instructor/_layout/sessions/'
    | '/instructor/_layout/courses/$courseId/manage'
    | '/_layout/courses/$courseId/learn/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRouteRoute: typeof LayoutRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  InstructorRoute: typeof InstructorRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/instructor': {
      id: '/instructor'
      path: '/instructor'
      fullPath: '/instructor'
      preLoaderRoute: typeof InstructorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/instructor/_layout': {
      id: '/instructor/_layout'
      path: '/instructor'
      fullPath: '/instructor'
      preLoaderRoute: typeof InstructorLayoutRouteRouteImport
      parentRoute: typeof InstructorRoute
    }
    '/instructor/_layout/': {
      id: '/instructor/_layout/'
      path: '/'
      fullPath: '/instructor/'
      preLoaderRoute: typeof InstructorLayoutIndexRouteImport
      parentRoute: typeof InstructorLayoutRouteRoute
    }
    '/_layout/sessions/': {
      id: '/_layout/sessions/'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof LayoutSessionsIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/messages/': {
      id: '/_layout/messages/'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof LayoutMessagesIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/home/': {
      id: '/_layout/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof LayoutHomeIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/courses/': {
      id: '/_layout/courses/'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof LayoutCoursesIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/account/': {
      id: '/_layout/account/'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof LayoutAccountIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/instructor/_layout/sessions/': {
      id: '/instructor/_layout/sessions/'
      path: '/sessions'
      fullPath: '/instructor/sessions'
      preLoaderRoute: typeof InstructorLayoutSessionsIndexRouteImport
      parentRoute: typeof InstructorLayoutRouteRoute
    }
    '/instructor/_layout/messages/': {
      id: '/instructor/_layout/messages/'
      path: '/messages'
      fullPath: '/instructor/messages'
      preLoaderRoute: typeof InstructorLayoutMessagesIndexRouteImport
      parentRoute: typeof InstructorLayoutRouteRoute
    }
    '/instructor/_layout/courses/': {
      id: '/instructor/_layout/courses/'
      path: '/courses'
      fullPath: '/instructor/courses'
      preLoaderRoute: typeof InstructorLayoutCoursesIndexRouteImport
      parentRoute: typeof InstructorLayoutRouteRoute
    }
    '/instructor/_layout/account/': {
      id: '/instructor/_layout/account/'
      path: '/account'
      fullPath: '/instructor/account'
      preLoaderRoute: typeof InstructorLayoutAccountIndexRouteImport
      parentRoute: typeof InstructorLayoutRouteRoute
    }
    '/_layout/courses/$courseId/': {
      id: '/_layout/courses/$courseId/'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof LayoutCoursesCourseIdIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/courses/$courseId/learn/': {
      id: '/_layout/courses/$courseId/learn/'
      path: '/courses/$courseId/learn'
      fullPath: '/courses/$courseId/learn'
      preLoaderRoute: typeof LayoutCoursesCourseIdLearnIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/instructor/_layout/courses/$courseId/manage': {
      id: '/instructor/_layout/courses/$courseId/manage'
      path: '/courses/$courseId/manage'
      fullPath: '/instructor/courses/$courseId/manage'
      preLoaderRoute: typeof InstructorLayoutCoursesCourseIdManageRouteImport
      parentRoute: typeof InstructorLayoutRouteRoute
    }
  }
}

interface LayoutRouteRouteChildren {
  LayoutAccountIndexRoute: typeof LayoutAccountIndexRoute
  LayoutCoursesIndexRoute: typeof LayoutCoursesIndexRoute
  LayoutHomeIndexRoute: typeof LayoutHomeIndexRoute
  LayoutMessagesIndexRoute: typeof LayoutMessagesIndexRoute
  LayoutSessionsIndexRoute: typeof LayoutSessionsIndexRoute
  LayoutCoursesCourseIdIndexRoute: typeof LayoutCoursesCourseIdIndexRoute
  LayoutCoursesCourseIdLearnIndexRoute: typeof LayoutCoursesCourseIdLearnIndexRoute
}

const LayoutRouteRouteChildren: LayoutRouteRouteChildren = {
  LayoutAccountIndexRoute: LayoutAccountIndexRoute,
  LayoutCoursesIndexRoute: LayoutCoursesIndexRoute,
  LayoutHomeIndexRoute: LayoutHomeIndexRoute,
  LayoutMessagesIndexRoute: LayoutMessagesIndexRoute,
  LayoutSessionsIndexRoute: LayoutSessionsIndexRoute,
  LayoutCoursesCourseIdIndexRoute: LayoutCoursesCourseIdIndexRoute,
  LayoutCoursesCourseIdLearnIndexRoute: LayoutCoursesCourseIdLearnIndexRoute,
}

const LayoutRouteRouteWithChildren = LayoutRouteRoute._addFileChildren(
  LayoutRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface InstructorLayoutRouteRouteChildren {
  InstructorLayoutIndexRoute: typeof InstructorLayoutIndexRoute
  InstructorLayoutAccountIndexRoute: typeof InstructorLayoutAccountIndexRoute
  InstructorLayoutCoursesIndexRoute: typeof InstructorLayoutCoursesIndexRoute
  InstructorLayoutMessagesIndexRoute: typeof InstructorLayoutMessagesIndexRoute
  InstructorLayoutSessionsIndexRoute: typeof InstructorLayoutSessionsIndexRoute
  InstructorLayoutCoursesCourseIdManageRoute: typeof InstructorLayoutCoursesCourseIdManageRoute
}

const InstructorLayoutRouteRouteChildren: InstructorLayoutRouteRouteChildren = {
  InstructorLayoutIndexRoute: InstructorLayoutIndexRoute,
  InstructorLayoutAccountIndexRoute: InstructorLayoutAccountIndexRoute,
  InstructorLayoutCoursesIndexRoute: InstructorLayoutCoursesIndexRoute,
  InstructorLayoutMessagesIndexRoute: InstructorLayoutMessagesIndexRoute,
  InstructorLayoutSessionsIndexRoute: InstructorLayoutSessionsIndexRoute,
  InstructorLayoutCoursesCourseIdManageRoute:
    InstructorLayoutCoursesCourseIdManageRoute,
}

const InstructorLayoutRouteRouteWithChildren =
  InstructorLayoutRouteRoute._addFileChildren(
    InstructorLayoutRouteRouteChildren,
  )

interface InstructorRouteChildren {
  InstructorLayoutRouteRoute: typeof InstructorLayoutRouteRouteWithChildren
}

const InstructorRouteChildren: InstructorRouteChildren = {
  InstructorLayoutRouteRoute: InstructorLayoutRouteRouteWithChildren,
}

const InstructorRouteWithChildren = InstructorRoute._addFileChildren(
  InstructorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRouteRoute: LayoutRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  InstructorRoute: InstructorRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
