export const cloudinaryConfig = {
  CLOUDINARY_CLOUD_NAME: process.env.CLOUDINARY_CLOUD_NAME!,
  CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY!,
  CLOUDINARY_API_SECRET: process.env.CLOUDINARY_API_SECRET!,

  CLOUDINARY_DEFAULT_SIGNATURE_EXPIRES_IN_SECONDS: 3600,
};
