export const ENROLLMENTS_TOPIC = 'ENROLLMENTS_TOPIC';
export const USERS_TOPIC = 'USERS_TOPIC';
export const INSTRUCTOR_TOPIC = 'INSTRUCTOR_TOPIC';
export const SESSION_TOPIC = 'SESSION_TOPIC';
export const COURSES_TOPIC = 'COURSES_TOPIC';
