export enum SessionStatus {
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  BOOKED = 'BOOKED',
  CONFIRMED = 'CONFIRMED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  RESCHEDULED = 'RESCHEDULED',
  NO_SHOW = 'NO_SHOW',
  INSTRUCTOR_NO_SHOW = 'INSTRUCTOR_NO_SHOW',
  PAYMENT_EXPIRED = 'PAYMENT_EXPIRED',
}
