export enum Currency {
  // Major World Currencies
  USD = 'USD', // United States Dollar
  EUR = 'EUR', // Euro
  JPY = 'JPY', // Japanese Yen
  GBP = 'GBP', // British Pound Sterling
  AUD = 'AUD', // Australian Dollar
  CAD = 'CAD', // Canadian Dollar
  CHF = 'CHF', // Swiss Franc
  CNY = 'CNY', // Chinese Yuan Renminbi
  SEK = 'SEK', // Swedish Krona
  NZD = 'NZD', // New Zealand Dollar

  // Other Common Currencies
  AED = 'AED', // United Arab Emirates Dirham
  AFN = 'AFN', // Afghan Afghani
  ALL = 'ALL', // Albanian Lek
  AMD = 'AMD', // Armenian Dram
  ANG = 'ANG', // Netherlands Antillean Guilder
  AOA = 'AOA', // Angolan Kwanza
  ARS = 'ARS', // Argentine Peso
  AWG = 'AWG', // Aruban Florin
  AZN = 'AZN', // Azerbaijani Manat
  BAM = 'BAM', // Bosnia and Herzegovina Convertible Mark
  BBD = 'BBD', // Barbadian Dollar
  BDT = 'BDT', // Bangladeshi Taka
  BGN = 'BGN', // Bulgarian Lev
  BHD = 'BHD', // Bahraini Dinar
  BIF = 'BIF', // Burundian Franc
  BMD = 'BMD', // Bermudian Dollar
  BND = 'BND', // Brunei Dollar
  BOB = 'BOB', // Bolivian Boliviano
  BRL = 'BRL', // Brazilian Real
  BSD = 'BSD', // Bahamian Dollar
  BTN = 'BTN', // Bhutanese Ngultrum
  BWP = 'BWP', // Botswana Pula
  BYN = 'BYN', // Belarusian Ruble
  BZD = 'BZD', // Belize Dollar
  CDF = 'CDF', // Congolese Franc
  CLP = 'CLP', // Chilean Peso
  COP = 'COP', // Colombian Peso
  CRC = 'CRC', // Costa Rican Colon
  CUP = 'CUP', // Cuban Peso
  CVE = 'CVE', // Cape Verdean Escudo
  CZK = 'CZK', // Czech Koruna
  DJF = 'DJF', // Djiboutian Franc
  DKK = 'DKK', // Danish Krone
  DOP = 'DOP', // Dominican Peso
  DZD = 'DZD', // Algerian Dinar
  EGP = 'EGP', // Egyptian Pound
  ERN = 'ERN', // Eritrean Nakfa
  ETB = 'ETB', // Ethiopian Birr
  FJD = 'FJD', // Fijian Dollar
  FKP = 'FKP', // Falkland Islands Pound
  GEL = 'GEL', // Georgian Lari
  GHS = 'GHS', // Ghanaian Cedi
  GIP = 'GIP', // Gibraltar Pound
  GMD = 'GMD', // Gambian Dalasi
  GNF = 'GNF', // Guinean Franc
  GTQ = 'GTQ', // Guatemalan Quetzal
  GYD = 'GYD', // Guyanaese Dollar
  HKD = 'HKD', // Hong Kong Dollar
  HNL = 'HNL', // Honduran Lempira
  HRK = 'HRK', // Croatian Kuna
  HTG = 'HTG', // Haitian Gourde
  HUF = 'HUF', // Hungarian Forint
  IDR = 'IDR', // Indonesian Rupiah
  ILS = 'ILS', // Israeli New Shekel
  INR = 'INR', // Indian Rupee
  IQD = 'IQD', // Iraqi Dinar
  IRR = 'IRR', // Iranian Rial
  ISK = 'ISK', // Icelandic Króna
  JMD = 'JMD', // Jamaican Dollar
  JOD = 'JOD', // Jordanian Dinar
  KES = 'KES', // Kenyan Shilling
  KGS = 'KGS', // Kyrgystani Som
  KHR = 'KHR', // Cambodian Riel
  KMF = 'KMF', // Comorian Franc
  KRW = 'KRW', // South Korean Won
  KWD = 'KWD', // Kuwaiti Dinar
  KYD = 'KYD', // Cayman Islands Dollar
  KZT = 'KZT', // Kazakhstani Tenge
  LAK = 'LAK', // Laotian Kip
  LBP = 'LBP', // Lebanese Pound
  LKR = 'LKR', // Sri Lankan Rupee
  LRD = 'LRD', // Liberian Dollar
  LSL = 'LSL', // Lesotho Loti
  LYD = 'LYD', // Libyan Dinar
  MAD = 'MAD', // Moroccan Dirham
  MDL = 'MDL', // Moldovan Leu
  MGA = 'MGA', // Malagasy Ariary
  MKD = 'MKD', // Macedonian Denar
  MMK = 'MMK', // Myanmar Kyat
  MNT = 'MNT', // Mongolian Tögrög
  MOP = 'MOP', // Macanese Pataca
  MRO = 'MRO', // Mauritanian Ouguiya (old)
  MRU = 'MRU', // Mauritanian Ouguiya
  MUR = 'MUR', // Mauritian Rupee
  MVR = 'MVR', // Maldivian Rufiyaa
  MWK = 'MWK', // Malawian Kwacha
  MXN = 'MXN', // Mexican Peso
  MYR = 'MYR', // Malaysian Ringgit
  MZN = 'MZN', // Mozambican Metical
  NAD = 'NAD', // Namibian Dollar
  NGN = 'NGN', // Nigerian Naira
  NIO = 'NIO', // Nicaraguan Córdoba
  NOK = 'NOK', // Norwegian Krone
  NPR = 'NPR', // Nepalese Rupee
  OMR = 'OMR', // Omani Rial
  PAB = 'PAB', // Panamanian Balboa
  PEN = 'PEN', // Peruvian Sol
  PGK = 'PGK', // Papua New Guinean Kina
  PHP = 'PHP', // Philippine Peso
  PKR = 'PKR', // Pakistani Rupee
  PLN = 'PLN', // Polish Złoty
  PYG = 'PYG', // Paraguayan Guarani
  QAR = 'QAR', // Qatari Riyal
  RON = 'RON', // Romanian Leu
  RSD = 'RSD', // Serbian Dinar
  RUB = 'RUB', // Russian Ruble
  RWF = 'RWF', // Rwandan Franc
  SAR = 'SAR', // Saudi Riyal
  SBD = 'SBD', // Solomon Islands Dollar
  SCR = 'SCR', // Seychellois Rupee
  SDG = 'SDG', // Sudanese Pound
  SGD = 'SGD', // Singapore Dollar
  SHP = 'SHP', // Saint Helena Pound
  SLL = 'SLL', // Sierra Leonean Leone
  SOS = 'SOS', // Somali Shilling
  SRD = 'SRD', // Surinamese Dollar
  SSP = 'SSP', // South Sudanese Pound
  STD = 'STD', // São Tomé and Príncipe Dobra (old)
  STN = 'STN', // São Tomé and Príncipe Dobra
  SVC = 'SVC', // Salvadoran Colón
  SYP = 'SYP', // Syrian Pound
  SZL = 'SZL', // Eswatini Lilangeni
  THB = 'THB', // Thai Baht
  TJS = 'TJS', // Tajikistani Somoni
  TMT = 'TMT', // Turkmenistani Manat
  TND = 'TND', // Tunisian Dinar
  TOP = 'TOP', // Tongan Paʻanga
  TRY = 'TRY', // Turkish Lira
  TTD = 'TTD', // Trinidad and Tobago Dollar
  TWD = 'TWD', // New Taiwan Dollar
  TZS = 'TZS', // Tanzanian Shilling
  UAH = 'UAH', // Ukrainian Hryvnia
  UGX = 'UGX', // Ugandan Shilling
  UYU = 'UYU', // Uruguayan Peso
  UZS = 'UZS', // Uzbekistan Som
  VES = 'VES', // Venezuelan Bolívar Soberano
  VND = 'VND', // Vietnamese Đồng
  VUV = 'VUV', // Vanuatu Vatu
  WST = 'WST', // Samoan Tala
  XAF = 'XAF', // Central African CFA Franc
  XCD = 'XCD', // East Caribbean Dollar
  XOF = 'XOF', // West African CFA Franc
  XPF = 'XPF', // CFP Franc
  YER = 'YER', // Yemeni Rial
  ZAR = 'ZAR', // South African Rand
  ZMW = 'ZMW', // Zambian Kwacha
  ZWL = 'ZWL', // Zimbabwean Dollar
}
