import { envVariables } from '@/validation/env-variables';

export const cloudinaryConfig = {
  CLOUDINARY_CLOUD_NAME: envVariables.CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY: envVariables.CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET: envVariables.CLOUDINARY_API_SECRET,

  CLOUDINARY_DEFAULT_SIGNATURE_EXPIRES_IN_SECONDS:
    envVariables.CLOUDINARY_DEFAULT_SIGNATURE_EXPIRES_IN_SECONDS,
};
