export const ENROLLMENTS_TOPIC = "ENROLLMENTS_TOPIC";
export const NOTIFICATION_TOPIC = "NOTIFICATION_TOPIC";
export const COURSE_TOPIC = "COURSE_TOPIC";
export const SESSION_TOPIC = "SESSION_TOPIC";
